# Validate the goReleaser configuration

name: validate_goreleaser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate_goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.2

      - name: Download GoReleaser
        run: |
          mkdir ./bin && curl -sSLf https://github.com/goreleaser/goreleaser/releases/latest/download/goreleaser_Linux_x86_64.tar.gz -o - | tar --extract --gunzip --directory ./bin goreleaser
      - name: Check goreleaser validity
        run: |
          ./bin/goreleaser check
